on:
  push:
    paths:
      - build-package/**
      - tests/**
      - .github/workflows/build_package.yaml
  schedule:
    - cron: "0 0 1 * *"

name: Build package

jobs:

  build-package:

    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DEBIAN_FRONTEND: "noninteractive"
      QT_QPA_PLATFORM: "offscreen"
      XDG_RUNTIME_DIR: "/tmp"
      PYTHONPATH: "/usr/share/qgis/python/plugins:/usr/share/qgis/python"

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install QGIS
        run: |
          wget -qO - https://qgis.org/downloads/qgis-2021.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import || true
          sudo chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
          sudo add-apt-repository "deb https://qgis.org/ubuntu `lsb_release -c -s` main"
          sudo apt-get update
          sudo apt-get install -y qgis qgis-plugin-grass saga

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Install remotes and package build dependencies
        run: source("./build-package/install_save_deps.R")
        shell: Rscript {0}

      - name: Print QGIS info
        run: |
          #qgisprocess::qgis_run()
          #print("---------------------")
          print("Has QGIS:")
          print(qgisprocess::has_qgis())
          print(qgisprocess::qgis_configure())
          cat(qgisprocess::qgis_run("plugins")$stdout)
        shell: Rscript {0}

      - name: Delete all files in R
        run: |
          rm -f ./R/*.R
          rm -f ./man/*.Rd

      - name: Build Package functions in folder R and document them
        run: source("./build-package/build_QGIS_functions.R")
        shell: Rscript {0}

      - name: Add QGIS version to description
        run: source("./build-package/update_Description.R")
        shell: Rscript {0}

      - name: Package tests
        run: |
          devtools::test()
        shell: Rscript {0}

      - name: Check and install
        run: |
          devtools::build_vignettes()
          devtools::check()
          devtools::install()
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: "current update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
