on:
  push:
    paths:
      - build-package/**
      - tests/**
      - .github/workflows/**
      - NEWS.md
      - README.Rmd
  schedule:
    - cron: "0 0 1 * *"

name: Build package

jobs:

  build-package:

    runs-on: ubuntu-latest

    container: qgis/qgis:latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install R
        run: |
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
          apt install -y r-base pandoc git

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install remotes and package build dependencies
        run: source("./build-package/install_save_deps.R")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Install R dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          # remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Print QGIS info
        run: |
          qgisprocess::qgis_run()
          print("---------------------")
          print("Has QGIS:")
          print(qgisprocess::has_qgis())
          print(qgisprocess::qgis_configure())
          cat(qgisprocess::qgis_run("plugins")$stdout)
          qgisprocess::qgis_run("plugins enable grassprovider")
          qgisprocess::qgis_run("plugins enable sagaprovider")
          cat(qgisprocess::qgis_run("plugins")$stdout)
        shell: Rscript {0}

      - name: Delete all files in R
        run: |
          rm -f ./R/*.R
          rm -f ./man/*.Rd

      - name: Build Package functions in folder R and document them
        run: source("./build-package/build_QGIS_functions.R")
        shell: Rscript {0}

      - name: Add QGIS version to description
        run: source("./build-package/update_Description.R")
        shell: Rscript {0}

      - name: Check and install
        run: |
          devtools::build_vignettes()
          devtools::check()
          devtools::install()
        shell: Rscript {0}

      - name: Render README
        run: source("./build-package/render_README.R")
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v7.2.0
        with:
          default_author: github_actions
          message: "current update"
          pull_strategy: 'NO-PULL'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package website
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
