on:
  push:
    branches:
      - master
    paths:
      - man/**
      - vignettes/**
      - NEWS.md
      - README.Rmd
      - DESCRIPTION
      - .github/workflows/make_web.yaml

name: Make website

jobs:

  make-website:

    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install QGIS
        run: |
          wget -qO - https://qgis.org/downloads/qgis-2021.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import || true
          sudo chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
          sudo add-apt-repository "deb https://qgis.org/ubuntu `lsb_release -c -s` main"
          sudo apt-get update
          sudo apt-get install -y qgis qgis-plugin-grass saga

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::pkgdown
            any::devtools

      - name: Install package
        run: |
          devtools::install()
        shell: Rscript {0}

      - name: Render README
        run: source("./build-package/render_README.R")
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v7.2.0
        with:
          default_author: github_actions
          message: "current update"
          pull_strategy: 'NO-PULL'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package website
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
